[package]
name = "libav-sys"
version = "0.1.0"
authors = ["tarkah <tarkah@admin.dev>"]

build = "build.rs"

[build-dependencies]
bindgen = "0.53"
metadeps = "1.1"

[package.metadata.pkg-config]
libavcodec = "58"
libavformat = "58"
libavutil = "56"

[dependencies]
